### ISSUE TITLE
Run into panic:runtime error when trying to test sessions example code  with ApacheBench

### ISSUE THREAD

**Issue by Tanete** [kataras/go-sessions#6]
Get panic error like this when trying to test sessions code example by Apache Bench with  command like `ab -n 10000 -c 10 http://127.0.0.1:8080/get `.

* Iris Version: v4-LTS
* go-session version: v0.0.6

Could anyone reproduce this? Is this a bug?

Session example code  like this copied from [here](https://docs-v4.iris-go.com/package-sessions.html)
```go
package main

import "gopkg.in/kataras/iris.v4"

func main() {
	iris.Get("/", func(c *iris.Context) {
		c.Write("You should navigate to the /set, /get, /delete, /clear,/destroy instead")
	})

	iris.Get("/set", func(c *iris.Context) {

		//set session values
		c.Session().Set("name", "iris")

		//test if setted here
		c.Write("All ok session setted to: %s", c.Session().GetString("name"))
	})

	iris.Get("/get", func(c *iris.Context) {
		// get a specific key as a string.
		// returns an empty string if the key was not found.
		name := c.Session().GetString("name")

		c.Write("The name on the /set was: %s", name)
	})

	iris.Get("/delete", func(c *iris.Context) {
		// delete a specific key
		c.Session().Delete("name")
	})

	iris.Get("/clear", func(c *iris.Context) {
		// removes all entries
		c.Session().Clear()
	})

	iris.Get("/destroy", func(c *iris.Context) {
		// destroy/removes the entire session and cookie
		c.SessionDestroy()
		c.Log("You have to refresh the page to completely remove the session (on browsers), so the name should NOT be empty NOW, is it?\n ame: %s\n\nAlso check your cookies in your browser's cookies, should be no field for localhost/127.0.0.1 (or whatever you use)", c.Session().GetString("name"))
		c.Write("You have to refresh the page to completely remove the session (on browsers), so the name should NOT be empty NOW, is it?\nName: %s\n\nAlso check your cookies in your browser's cookies, should be no field for localhost/127.0.0.1 (or whatever you use)", c.Session().GetString("name"))
	})

	iris.Listen(":8080")
}
```

Error Info:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6f4cdd]
goroutine 35 [running]:
panic(0x9cdc00, 0xc42000c140)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
container/list.(*List).PushBack(0xc42017fbf0, 0xa41220, 0xc42042fe00, 0xc42042fe00)
        /usr/local/go/src/container/list/list.go:139 +0xdd
gopkg.in/kataras/go-sessions%2ev0.(*Provider).Init(0xc42017fc50, 0xc420015770, 0x2c, 0x68c61714000, 0x0, 0x8)
        /home/szp/gowp/src/gopkg.in/kataras/go-sessions.v0/provider.go:74 +0x9b
gopkg.in/kataras/go-sessions%2ev0.(*sessions).StartFasthttp(0xc4201d7380, 0xc420274000, 0x4, 0x4)
        /home/szp/gowp/src/gopkg.in/kataras/go-sessions.v0/sessions.go:212 +0xc0
gopkg.in/kataras/iris%2ev4.(*Context).Session(0xc420438940, 0x464a1d, 0xc42000c129)
        /home/szp/gowp/src/gopkg.in/kataras/iris.v4/context.go:1102 +0x6e
main.main.func3(0xc420438940)
        /home/szp/gowp/src/sessionTest/sessions.go:53 +0x2f
gopkg.in/kataras/iris%2ev4.HandlerFunc.Serve(0xacba98, 0xc420438940)
        /home/szp/gowp/src/gopkg.in/kataras/iris.v4/http.go:245 +0x30
gopkg.in/kataras/iris%2ev4.(*Context).Do(0xc420438940)
        /home/szp/gowp/src/gopkg.in/kataras/iris.v4/context.go:117 +0x49
gopkg.in/kataras/iris%2ev4.(*serveMux).BuildHandler.func1(0xc420438940)
        /home/szp/gowp/src/gopkg.in/kataras/iris.v4/http.go:1092 +0x88b
gopkg.in/kataras/iris%2ev4.(*Framework).Build.func1.1(0xc420274000)
        /home/szp/gowp/src/gopkg.in/kataras/iris.v4/iris.go:367 +0x5a
github.com/valyala/fasthttp.(*Server).serveConn(0xc4202168c0, 0xd498e0, 0xc4202b0018, 0xc420252001, 0xc420250101)
        /home/szp/gowp/src/github.com/valyala/fasthttp/server.go:1536 +0x573
github.com/valyala/fasthttp.(*Server).(github.com/valyala/fasthttp.serveConn)-fm(0xd498e0, 0xc4202b0018, 0xc420041f48, 0x1)
        /home/szp/gowp/src/github.com/valyala/fasthttp/server.go:1250 +0x3e
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc420252000, 0xc42025e120)
        /home/szp/gowp/src/github.com/valyala/fasthttp/workerpool.go:210 +0xde
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc420252000, 0xc42025e120, 0x97dc00, 0xc42025e120)
        /home/szp/gowp/src/github.com/valyala/fasthttp/workerpool.go:182 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /home/szp/gowp/src/github.com/valyala/fasthttp/workerpool.go:184 +0x111

```

**Comment by Tanete** [comment]
I upgraded go-sessions library, but still do not work. If nobody was seeing these error messages like me, it should be my own problem. 

I suppose it should be related with some library version mismatch and I will try to redeploy my Go dev environment. 

Thanks a lot.

**Comment by kataras** [comment]
I tested the same apache bench command on my pc and it's working fine ( all repositories points to master, github.com/kataras/$) I cannot test via gopkg.in right now because I do a lot of changes to these repo folders for testing :/
